"""Compile the textured-quad shaders and emit native/tex_shaders.h.

The native renderer embeds SPIR-V as uint32 arrays (see vulkan_init.c for the
solid-colour pair), so a shader change has to be regenerated into a header.
Run from native/:  python shaders/gen_spv.py

Requires glslangValidator (Vulkan SDK bin).
"""
import pathlib
import shutil
import subprocess
import sys

HERE = pathlib.Path(__file__).resolve().parent
OUT = HERE.parent / "tex_shaders.h"


def find_glslang():
    exe = shutil.which("glslangValidator")
    if exe:
        return exe
    for cand in pathlib.Path("C:/VulkanSDK").glob("*/Bin/glslangValidator.exe"):
        return str(cand)
    sys.exit("glslangValidator not found (install the Vulkan SDK)")


def compile_stage(exe, src, stage):
    spv = src.with_suffix(src.suffix + ".spv")
    subprocess.run([exe, "-V", str(src), "-o", str(spv), "--target-env", "vulkan1.0"],
                   check=True, capture_output=True)
    data = spv.read_bytes()
    if len(data) % 4:
        sys.exit(f"{spv} is not a whole number of words")
    words = [int.from_bytes(data[i:i + 4], "little") for i in range(0, len(data), 4)]
    spv.unlink()
    print(f"  {stage}: {len(words)} words")
    return words


def emit(name, words, stage):
    body = ",".join("0x%08x" % w for w in words)
    return (f"// {stage} stage, compiled from shaders/{name}\n"
            f"static const uint32_t {name.replace('.', '_')}_spv[] = {{\n    {body}\n}};\n")


def main():
    exe = find_glslang()
    pairs = [("tex.vert", "vert"), ("tex.frag", "frag")]
    chunks = []
    for fname, stage in pairs:
        words = compile_stage(exe, HERE / fname, stage)
        chunks.append(emit(fname, words, stage))
    OUT.write_text(
        "#ifndef TEX_SHADERS_H\n"
        "#define TEX_SHADERS_H\n"
        "#include <stdint.h>\n\n"
        "// GENERATED by shaders/gen_spv.py -- do not edit by hand.\n\n"
        + "\n".join(chunks) +
        "\n#endif\n",
        encoding="utf-8", newline="\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
